version: '3'
services:
  nest-api:
    container_name: nestServer-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3100:3100'
    env_file:
      - prisma/.env.docker
    depends_on:
      - postgres-db
      - redis
    volumes:
      - ./logs:/app/dist/logs
      - ./uploadResource:/app/dist/uploadResource
  postgres-db:
    image: postgres:10.3
    container_name: postgresDB-server
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - ./volumes/database_postgres-data:/var/lib/postgresql/data
  redis:
    image: registry.ebrserver:3060/library/redis:latest
    container_name: redisCache-server
    restart: always
    command: ['redis-server', '--appendonly', 'yes']
    hostname: redis
    volumes:
      - ./volumes/database_redis-data:/data
    ports:
      - '6379:6379'
networks:
  prisma:
    ipam:
      config:
        - subnet: 192.100.0.0/16
