version: '3'

services:
  nestjs-api:
    image: nestjs-api-dev:1.0.0
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: node dist/src/main
    ports:
      - 3100:3100
    volumes:
      - .:/usr/src/app/logs
networks:
  prisma:
    ipam:
      config:
        - subnet: 192.200.0.0/16
