# 服务配置（每个单独的服务都需要配置对应的端口）

serve:
  port: 3100
  prefix: # 路径前缀
  gqlAuth: false  #是否开启GraphQL鉴权认证
  graphqlPath: '/data/ff/graphql' #GraphQL请求路径  


# 缓存配置
cache:
  redis: # 有值时，使用 redis 做缓存服务器
    host: 'localhost'
    port: 6379
    db: 0

# 加密
encryption:
  saltOrRounds: 10

# Swagger 配置
swagger:
  title: 项目接口文档
  description: '[Base URL: localhost:3100]'
  path: v1/swagger

# 限流
httpLimiter:
  tokenKey: 'nestHttpLimiter' #剩余tokenKey
  timestampKey: 'nestHttpLimiterStamp' #刷新时间Key
  capacity: 10 #桶容量
  rate: 1 #每秒生成token数量即token生成速度
