# 服务配置（每个单独的服务都需要配置对应的端口）

serve:
  port: 3100
  prefix: # 路径前缀


db:
  postgres:
    url: 'localhost'
    port: 5432
    database: 'yaml-db'

  sqlite:
    database: 'sqlite.db'
    
# 缓存配置

cache:
  redis: # 有值时，使用 redis 做缓存服务器
    host: 'localhost'
    port:

# 加密
encryption:
  saltOrRounds: 10

# Swagger 配置

swagger:
  title: 项目接口文档
  description: '[Base URL: localhost:3001]'
  path: v1/swagger

# 日志存放目录

logsPath: apps